# 基础镜像
FROM redis
# author
MAINTAINER graython

# 挂载目录
VOLUME /home/graython/redis
# 创建目录
RUN mkdir -p /home/graython/redis
# 指定路径
WORKDIR /home/graython/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/graython/redis/redis.conf
