# Tomcat
server: 
  port: 8080

# Spring
spring: 
  application:
    # 应用名称
    name: graython-gateway
  profiles:
    # 环境配置
    active: dev
  main:
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。
    allow-bean-definition-overriding: true # 允许 Bean 覆盖，例如说 Feign 等会存在重复定义的服务

  config:
    import:
      - optional:classpath:application-${spring.profiles.active}.yml # 加载【本地】配置
      - nacos:${spring.application.name}-${spring.profiles.active}.yml # 加载【Nacos】的配置