# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER graython

# 挂载目录
VOLUME /home/graython
# 创建目录
RUN mkdir -p /home/graython
# 指定路径
WORKDIR /home/graython
# 复制jar文件到路径
COPY ./jar/graython-visual-monitor.jar /home/graython/graython-visual-monitor.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","graython-visual-monitor.jar"]