spring:
  redis:
    host: 192.168.31.77
    port: 6379
    database: 4
    password: Redis@123456 # Redis密码（如果没有可以不填）
    timeout: 5000ms  # 超时时间
    lettuce:
      pool:
        max-active: 8  # 连接池最大连接数
        max-idle: 8    # 连接池最大空闲连接数
        min-idle: 0    # 连接池最小空闲连接数
