# Spring
spring:
  cloud:
    nacos:
      # 服务注册地址
      username: nacos    # 如果启用了 Nacos 认证
      password: nacos
      server-addr: 192.168.31.77:8848    # Nacos 服务器地址
      discovery:
        group: DEFAULT_GROUP
        namespace: public
        metadata:
          version: 1.0.0 # 服务实例的版本号，可用于灰度发布
      config:
        # 禁用自动加载默认配置
        import-check:
          enabled: false
        enabled: true
        namespace: public
        group: DEFAULT_GROUP
        # 配置文件格式
        file-extension: yml


